#+OPTIONS: num:nil author:nil timestamp:nil

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

** No.152

$a + b + c \leq \lfloor L/4 \rfloor$ となるピタゴラス数を数え上げる。

ピタゴラス数の数え上げは

$(a, b, c) = (m^2 - n^2, 2mn, m^2 + n^2)$ (ただし、$m \gt n$, $m$ と $n$ は互いに素、$m - n$ は奇数)

を使う。$2m^2 \leq L/4$ であるから、$m$ は最大でも $10^3$ 強である。

** No.153

grundy 数を計算する。

$g(1) = 0$ であり、山が $x_1, x_2$ 個の山に分裂したときの grundy 数は $g(x_1) \oplus g(x_2)$ となる。

** No.154

後ろの文字から見ていき、Rが通過した系統数 $R$ 、Gが通過した系統数 $G$ 、Wが通過した系統数 $W$ をメモしておく。文字によってメモを以下のように更新する。

- Rのときは $R$ に $1$ を加える。
- Gのときは $G \geq R$ ならば impossible。そうでなければ $G$ に $1$ を加える。
- Wのときは $G = 0$ ならば impossible。そうでなければ $W$ に $1$ を加える。ただし加えた結果 $W \gt G$ となる場合は加えない。

最後まで見終わったときに $R = G = W$ ならば possible、そうでなければ impossible である。

** No.156

実装あるのみ。

** No.157

空洞をひとつ選び、そこから空洞を深さ(幅)優先探索で探索してかたまり1を確定させる。

残りの中から空洞をひとつ選び、そこから深さ(幅)優先探索でかたまり2を確定させていく。探索の途中で壁があった場合は、そこから幅優先探索でかたまり1にたどり着くまでの最短距離を求める。

すべての最短距離の最小値が答えである。

** No.158

手持ちが $(A_{1000}, A_{100}, A_1)$ のときに行ける最大のお使い回数を返す関数を作り、メモ化再帰する。

$D$ 円を払うための1000円、100円、1円の使い方は、大きい方のお金から使うようにすればいい。合計金額が足りているがちょうど払えない場合は大きい方のお金を持っているときだからである。

** No.159

以下の計算式になる。

\begin{align*}
P_1 &= (1-p)q \\
P_2 &= p(1-q)q
\end{align*}

$q \neq 0$ であるので、$q$ で割っておいていい。

** No.160

ダイクストラ法で各駅からゴールまでの最小距離を求める。

その後、スタートから辞書順で小さい番号の駅でゴールまでの最小距離が一致する駅を順にたどる。

** No.161

友人の手に勝てるカードをできるだけ出し、その後引き分けになるカードをできるだけ出す。

** No.163

実装あるのみ。

** Local variables                                                 :noexport:

# Local variables:
# after-save-hook: org-html-export-to-html
# end:
