#+OPTIONS: num:nil author:nil timestamp:nil

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

** No.101

$i$ 番目からスタートしたときのゴール番号をシミュレーションで計算する。

$i$ 番目からスタートしたときにあみだくじをいくつつなげれば再び $i$ 番目に戻るかを計算する。

$1 \cdots N$ 番目の必要なあみだくじの数の最小公倍数が答えである。

** No.102

最後の山の最後のカードを取ると、相手のカードを少なくとも半分以上奪えるので、最後の山の最後のカードを取った人の勝ちである。

あとは grundy 数を計算すればいい。

** No.103

素因数の乗数をカードの枚数と考えれば No.102 とほぼ同様の問題となる。

** No.104

$i$ 号線は左は $2i$ 号線、右は $2i+1$ 号線に分岐する。

あとはシミュレーションを行う。

** No.105

角度は $\tan^{-1}(y/x)$ で求める。(たいていの言語には =atan2= があると思われる)

$0 \cdots 360^\circ$ の範囲に収まるように調整し、ソートした最初の角度が求める角度である。

ただし、誤差の関係で $50^\circ$ を超えることがあるので、その場合は $0^\circ$ が答えとなる。

** No.106

エラトステネスの篩を改造して素因数の数を数えられるようにする。

** No.107

それまでに相手をしたモンスターの集合 $S$ として、そのときの取りうる最大体力を $H(S)$ とする。

$H(S)$ は $H(S - m_i)$ (ただし $m_i \in S$) から求められる。(それまでに相手をしたモンスターの集合からレベルも求められる)

最後に $H(T)$ ($T$ はすべてのモンスターの集合) を見る。

** No.108

$i$ 枚 ($0 \leq i \leq 2$) 持っているカードの種類数を $x_i$ として、このときのコンプリートまで購入するカード枚数の期待値を $E(x_0, x_1, x_2)$ とすると、

\[ E(x_0, x_1, x_2) = E(x_0 - 1, x_1 + 1, x_2) \frac{x_0}{N} + E(x_0, x_1 - 1, x_2 + 1) \frac{x_1}{N} + E(x_0, x_1, x_2 - 1) \frac{x_2}{N} + E(x_0, x_1, x_2) \frac{N - x_s}{N} + 1 \]

となる。ただし、 $x_s = x_0 + x_1 + x_2$ である。これを変形して、

\[ E(x_0, x_1, x_2) = (E(x_0 - 1, x_1 + 1, x_2) x_0 + E(x_0, x_1 - 1, x_2 + 1) x_1 + E(x_0, x_1, x_2 - 1) x_2 + N) \frac{1}{x_s} \]

となる。ただし、$E(0, 0, 0) = 0$ である。

これをメモ化再帰で計算する。

** No.110

最初に白を使うとする。このとき、白の最大の長さの棒を使う。次に使う黒の棒は直前の白の長さより短い長さの棒のうちの最大の長さの棒である。以下これを繰り返して何本使えるかを計算する。

最初に黒を使う場合も同様に計算し、より大きい高さが答えである。

** No.111

$i$ 文字目から始まる回文数 $S_i$ は、$k = (L - 1) / 2$ とすると、

\begin{align*}
S_j &= k - j + 1 & (j = 2i - 1) \\
S_j &= k - j     & (j = 2i)
\end{align*}

となる。ただし、$1 \leq j \leq k$ である。よって、すべての回文数は、

\[ S = \sum_{j=1}^k S_j = 2k^2 - k(k+1) + k = k^2 \]

となる。

** No.112

$i$ 番目の動物の足の数を $b_i$ として、 $S = \sum b_i$ とすると、

\[ a_i = S - b_i \]

となる。両辺をすべての $i$ について足すと、

\[ \sum a_i = NS - S = (N-1)S \]

となる。ここから $S$ が求め、$b_i$ を求める。

** No.113

実装あるのみ。

** No.115

最初に $1, 2, \cdots, K$ 円を買ったとする。これが $D$ 円以下なら、最後の $K$ 円のお菓子をより高いお菓子に切り替える。一番高いお菓子に切り替えても $D$ 円に届いていないならば、$K-1$ 円のお菓子をより高いお菓子に切り替える。

以下これを繰り返す。

** No.116

実装あるのみ。

** No.117

\begin{align*}
C(n, k) &= \frac{n!}{k!(n-k)!} \\
P(n, k) &= \frac{n!}{(n-k)!} \\
H(n, k) &= C(n+k-1, k) \\
        &= \frac{(n+k-1)!}{k!(n-1)!}
\end{align*}

である。ここで $p = 10^9 + 7$ とすると、$p$ は素数であるので剰余環 $\mathbb{Z}/p\mathbb{Z}$ の要素には逆元が存在し、その値は拡張ユークリッドの互除法で計算することができる。

ここで剰余環 $\mathbb{Z}/p\mathbb{Z}$ 上で $n!$ およびその逆元をあらかじめ求めておけば、上記の計算はすべて $O(1)$ で可能である。

** No.118

選んだ竹の長さがすべて異なっていればいい。

$N$ 本から $3$ を選ぶ組み合わせの数は ${}_NC_3$ である。ここから同じ長さの竹を選ぶ組み合わせを差し引く。

$k$ 本同じ長さの竹がある場合、そのうちの $2$ 本が入っている組み合わせの数は ${}_kC_2 (N-k)$　であり、$3$ 本が入っている組み合わせの数は ${}_kC_3$ である。

${}_nC_r$ の $r$ は $2$ か $3$ であり、$N \leq 10^5$ であるから計算はすべて long の範囲で収まる。

** Local variables                                                 :noexport:

# Local variables:
# after-save-hook: org-html-export-to-html
# end:

