title: 競技プログラミングの問題を解いてみたメモ
baseurl: /procon
github_username: te-sh

collections:
  yukicoder:
    output: true
  abc:
    output: true
  arc:
    output: true

defaults:
  - scope:
      path: ""
      type: yukicoder
    values:
      layout: yukicoder
      subtitle: yukicoder
  - scope:
      path: ""
      type: abc
    values:
      layout: abc
      subtitle: AtCoder Beginner Contest
      a2n:
        A: 1
        B: 2
        C: 3
        D: 4
  - scope:
      path: ""
      type: arc
    values:
      layout: arc
      subtitle: AtCoder Regular Contest
      a2n:
        A: 1
        B: 2
        C: 3
        D: 4

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
