title: 競技プログラミングの問題を解いてみたメモ
baseurl: /procon
github_username: te-sh

collections:
  yukicoder:
    output: true

defaults:
  - scope:
      path: ""
      type: yukicoder
    values:
      layout: yukicoder
      subtitle: yukicoder

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
