title: 競技プログラミングの問題を解いてみたメモ
baseurl: /procon
github_username: te-sh

collections:
  memos:
    output: true

defaults:
  - scope:
      path: ""
      type: memos
    values:
      layout: page

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
